#cloud-config
apt_sources:
  - source: "ppa:saltstack/salt"
packages:
  - python-software-properties
  - git
  - salt-master
  - salt-minion
  - make
write_files:
  - content: |
        roles:
           - hadoop_master
        hdfs_data_disks:
           - /mnt
    path: /etc/salt/grains
  - content: |
        #!/bin/bash
        sed -i 's/^#auto_accept.*$/auto_accept: True/g' /etc/salt/master
        sudo service salt-master restart
    path: /tmp/bootstrap-master.sh
    permissions: "0755"
  - content: |
        #!/bin/bash
        sed -i 's/^#master.*$/master: 127.0.0.1/g' /etc/salt/minion
        sudo service salt-minion restart
    path: /tmp/bootstrap-minion.sh
    permissions: "0755"
  - content: |
      file_roots:
        base:
          - /srv/salt
          - /srv/salt/formulas/hadoop-formula
          - /srv/salt/formulas/hostsfile-formula
          - /srv/salt/formulas/sun-java-formula
    path: /etc/salt/master.d/file_roots.conf
    permissions: '0644'
  - content: |
      pillar_roots:
        base:
          - /srv/pillar
    path: /etc/salt/master.d/pillar_roots.conf
  - content: |
      base:
        'G@roles:hadoop_slave or G@roles:hadoop_master':
          - match: compound
          - hostsfile
          - hostsfile.hostname
          - sun-java
          - sun-java.env
          - hadoop
          - hadoop.hdfs
          - hadoop.yarn
          - hadoop.spark
    path: /srv/salt/top.sls
  - content: |
      base:
        'G@roles:hadoop_slave or G@roles:hadoop_master':
           - hadoop
    path: /srv/pillar/top.sls
  - content: |
      hadoop:
        version: apache-2.7.1 # ['apache-1.2.1', 'apache-2.2.0', 'hdp-1.3.0', 'hdp-2.2.0', 'cdh-4.5.0', 'cdh-4.5.0-mr1']
        users:
          hadoop: 6000
          hdfs: 6001
          yarn: 6003
      spark:
        version: 1.6.0-bin-hadoop2.6
      yarn:
        resourcemanager_target: "roles:hadoop_master"
        nodemanager_target: "roles:hadoop_slave"
        config:
          yarn-site:
            yarn.nodemanager.aux-services:
              value: mapreduce_shuffle
            yarn.nodemanager.aux-services.mapreduce.shuffle.class:
              value: org.apache.hadoop.mapred.ShuffleHandler
            yarn.resourcemanager.scheduler.class:
              value: org.apache.hadoop.yarn.server.resourcemanager.scheduler.capacity.CapacityScheduler
          capacity-scheduler:
            yarn.scheduler.capacity.maximum-applications:
              value: 10000
            yarn.scheduler.capacity.resource-calculator:
              value: org.apache.hadoop.yarn.util.resource.DefaultResourceCalculator
            yarn.scheduler.capacity.root.queues:
              value: default,customqueue
            yarn.scheduler.capacity.root.capacity:
              value: 100
            yarn.scheduler.capacity.root.default.capacity:
              value: 70
            yarn.scheduler.capacity.root.default.user-limit-factor:
              value: 1
            yarn.scheduler.capacity.root.default.maximum-capacity:
              value: 100
            yarn.scheduler.capacity.root.default.state:
              value: RUNNING
            yarn.scheduler.capacity.root.default.acl_submit_applications:
              value: '*'
            yarn.scheduler.capacity.root.default.acl_administer_queue:
              value: '*'
            yarn.scheduler.capacity.root.customqueue.capacity:
              value: 30
            yarn.scheduler.capacity.root.customqueue.maximum-am-resource-percent:
              value: 1.0
            yarn.scheduler.capacity.root.customqueue.user-limit-factor:
              value: 1
            yarn.scheduler.capacity.root.customqueue.maximum-capacity:
              value: 100
            yarn.scheduler.capacity.root.customqueue.state:
              value: RUNNING
            yarn.scheduler.capacity.root.customqueue.acl_submit_applications:
              value: '*'
            yarn.scheduler.capacity.root.customqueue.acl_administer_queue:
              value: '*'
            yarn.scheduler.capacity.node-locality-delay:
              value: -1
    path: /srv/pillar/hadoop.sls
  - content: |
        mine_functions:
            network.interfaces: []
            network.ip_addrs: []
            grains.items: []
    path: /etc/salt/minion.d/mine_functions.conf

runcmd:
  - bash /tmp/bootstrap-master.sh
  - bash /tmp/bootstrap-minion.sh
  - git clone https://github.com/cgeroux/hadoop-formula.git /srv/salt/formulas/hadoop-formula
  - git clone https://github.com/cgeroux/hostsfile-formula.git /srv/salt/formulas/hostsfile-formula
  - git clone https://github.com/cgeroux/sun-java-formula.git /srv/salt/formulas/sun-java-formula
  - git clone https://github.com/cgeroux/init-salt.git /tmp/salt-init
  - sudo service salt-master restart
  - cd /srv/salt/formulas/hadoop-formula/hadoop/files;./generate_keypairs.sh
  - /tmp/salt-init/salt-init.py MINIONLIST
