#cloud-config
apt_sources:
  - source: "ppa:saltstack/salt"
packages: 
  - python-software-properties
  - salt-minion
fs_setup:
  - label: None
    filesystem: 'ext4'
    device: '/dev/vdb1'
    partition: 'auto'
mounts:
 - [ /dev/vdb1, /mnt, "ext4", "defaults,noatime"]
mount_default_fields: [ None, None, "ext4", "defaults,noatime", "0", "2"]
write_files: 
  - content: |
         roles:
            - hadoop_slave
            - spark_target
         hdfs_data_disks:
            - /mnt
    path: /etc/salt/grains
  - content: |
        #!/bin/bash
        sed -i 's/^#master.*$/master: IPTOREPLACE/g' /etc/salt/minion
        sudo service salt-minion restart
    path: /tmp/bootstrap-minion.sh
    permissions: "0755"
  - content: |
        mine_functions:
            network.interfaces: []
            network.ip_addrs: []
            grains.items: []
    path: /etc/salt/minion.d/mine_functions.conf
runcmd: 
 - bash /tmp/bootstrap-minion.sh
