#cloud-config
apt_sources:
 - source: "ppa:saltstack/salt"
packages: 
  - python-software-properties
  - salt-minion

runcmd: 
 - bash /tmp/bootstrap-minion.sh

write_files: 
  - content: |
        #!/bin/bash
        sed -i 's/^#master.*$/master: IPTOREPLACE/g' /etc/salt/minion
        sudo service salt-minion restart
    path: /tmp/bootstrap-minion.sh
    permissions: "0755"